# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='usertype',
            field=models.CharField(choices=[('S', 'Student'), ('I', 'Instructor')], default='S', max_length=1),
        ),
    ]
