# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_signup_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='usertype',
        ),
    ]
