# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_signup_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
