# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_the_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='the_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='the_user',
        ),
    ]
